# Generated by Django 5.1.2 on 2024-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('cnic', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('rent', models.CharField(max_length=150)),
                ('room', models.CharField(max_length=150)),
                ('vacancy', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterHostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cnic', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/media/')),
                ('location', models.CharField(max_length=150)),
                ('vacancy', models.CharField(max_length=150)),
                ('rent', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
